# Read the official documentation here : https://learn.microsoft.com/en-us/azure/defender-for-cloud/quickstart-onboard-github

name: "PS Test DevOps-SelfHosted"
on: push

jobs:
  MSDO:
    # currently only windows latest is supported
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
#    - uses: actions/setup-dotnet@v3
#      with:
#        dotnet-version: |
#          5.0.x
#          6.0.x
#    - name: Azure PowerShell Action
#      uses: Azure/powershell@v1.2.0
#      with:
#        # Specify the Az PowerShell script here.
#        inlineScript: |
#          Get-ChildItem env:* | sort-object name | select-object name, value
#        azPSVersion: "latest"
#        errorActionPreference: continue
    - name: Run Microsoft Security DevOps
      uses: microsoft/security-devops-action@v1.7.2
      id: msdo
      with:
        tools: bandit,credscan,eslint,templateanalyzer,terrascan
    - name: Upload alerts file as a workflow artifact
      uses: actions/upload-artifact@v3
      with:  
        name: alerts
        path: ${{ steps.msdo.outputs.sarifFile }}
